### ISSUE TITLE
PHP Pecl

### ISSUE THREAD

**Issue by Nirjonadda** [maxmind/GeoIP2-php#104]
Do you have plan to update PHP Pecl stable Version? Version 1.1.1 still in beta? No releases available for package "pecl.php.net/geoip"? Also update PHP 7.2 Support ?

**Comment by horgh** [comment]
The geoip package on PECL is not published by us. Also, it appears to be a version of the API for our legacy database format whereas this repository is for our newer GeoIP2 databases. Rather than PECL we publish this package to Packagist (Composer), so I'd recommend using that.

If there's a problem with newer versions of PHP we'd certainly like to know about it so we can fix it!
