### ISSUE TITLE
Fatal error: Declaration of GeoIp2\WebService\Client::country(string $ipAddress = 'me'): GeoIp2\Model\Country must be compatible with GeoIp2\ProviderInterface::country($ipAddress)

### ISSUE THREAD

**Issue by rupchy** [maxmind/GeoIP2-php#170]

**Comment by rupchy** [comment]
Okay, thanks a lot for looking into this. I will try your suggestion.

**Comment by oschwald** [comment]
I am going to close this as there is nothing we can do about it. Plugin authors should probably be using something like [PHP-Scoper](https://github.com/humbug/php-scoper) on their dependencies to prevent collisions like this.

**Comment by andrewjmead** [comment]
Keep in mind that GeoIp2 does not scopper PHP Scoper out of the box. You'll need to use patchers (a PHP Scoper feature) to get this done. This is because the library code constructs namspace/class strings with PHP Scoper cannot target.

Here's an example I created to patch Reader.php, though it appears there are other files that use `$class = 'GeoIp2...`.

```php
    'patchers' => [
        static function (string $filePath, string $prefix, string $contents): string {
            $parts = explode('vendor', $filePath);

            // Fix an issue with geoip2 where the reader has string class names
            if ($parts[1] === '/geoip2/geoip2/src/Database/Reader.php') {
                return preg_replace(
                    '%\$class = \'GeoIp2%',
                    '$class = \'' . $prefix . '\\\\GeoIp2',
                    $contents
                );
            }

            return $contents;
        },
    ],
```

**Comment by oschwald** [comment]
If you open a separate issue, I think we could easily fix the problem with the stringy class names.
